version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "live"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "live"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
