name: Cache

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  node:
    name: Node
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Cache Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

  trunk:
    name: Trunk
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Node Dependencies
        run: npm ci
      - name: Cache & Upload Trunk
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
