# Build (and cache?)
# Integration Test

name: Integrate

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - run: bash scripts/setup.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: bash scripts/build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: bash scripts/test.sh
