# Build (and cache?)
# Integration Test

name: Integrate

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yaml

  build:
    needs: setup
    name: Build
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    name: Test
    uses: ./.github/workflows/test.yaml
