name: Integrate

on:
  pull_request:
    branches:
      - main

env:
  NODE_ENV: development

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    container: node:18-bullseye-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Audit
        run: npm run audit

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   container: node:18-bullseye-slim
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Lint
  #       run: npm run lint git diff --diff-filter=ACMR --name-only main...${{ github.ref_name }}

  # format:
  #   name: Format
  #   runs-on: ubuntu-latest
  #   container: node:18-bullseye-slim
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Format
  #       run: npm run format git diff --diff-filter=ACMR --name-only main...${{ github.ref_name }}

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   container: node:18-bullseye-slim
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Test
  #       run: npm run test -- --onlyChanged

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            npm ci
            npm run lint git diff --diff-filter=ACMR --name-only main...${{ github.ref_name }}
