name: Setup

on:
  workflow_call:

jobs:
  install_node_dependencies:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    container: debian:11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm ci
