name: Setup

on:
  workflow_call:

jobs:
  install_node_dependencies:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      # - name: Install Node Dependencies
      #   run: npm ci
